// This file is auto-generated by @hey-api/openapi-ts

export const ChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message',
            description: 'The user\'s natural language input.'
        },
        thread_id: {
            type: 'string',
            title: 'Thread Id',
            description: 'The conversation thread ID for LangGraph memory persistence.',
            default: 'default'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'ChatRequest'
} as const;

export const ContactSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: [
        'name',
        'email'
    ],
    title: 'Contact',
    description: 'A contact in the Contacts sheet.'
} as const;

export const ContactCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: [
        'name',
        'email'
    ],
    title: 'ContactCreate',
    description: 'Request body for creating a new contact.'
} as const;

export const ContactUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'ContactUpdate',
    description: 'Request body for updating a contact. All fields optional.'
} as const;

export const CreatePaymentLinkRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        min_partial_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Partial Amount'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: [
        'name',
        'email',
        'amount',
        'description'
    ],
    title: 'CreatePaymentLinkRequest',
    description: 'Request body for creating a Razorpay payment link.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const PaymentSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        razorpay_link_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Razorpay Link Id'
        },
        razorpay_link_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Razorpay Link Url'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'partial',
                'paid',
                'failed'
            ],
            title: 'Status',
            default: 'pending'
        },
        amount_paid: {
            type: 'number',
            title: 'Amount Paid',
            default: 0
        },
        due_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        created_at: {
            type: 'string',
            title: 'Created At',
            default: ''
        },
        last_reminder_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Reminder At'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: [
        'name',
        'email',
        'amount',
        'description'
    ],
    title: 'Payment',
    description: 'A payment record from the Payments sheet.'
} as const;

export const PaymentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        min_partial_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Partial Amount'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: [
        'name',
        'email',
        'amount',
        'description'
    ],
    title: 'PaymentCreate',
    description: 'Request body for creating a new payment record.'
} as const;

export const PaymentLinkResponseSchema = {
    properties: {
        link_id: {
            type: 'string',
            title: 'Link Id'
        },
        short_url: {
            type: 'string',
            title: 'Short Url'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency',
            default: 'INR'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        customer_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Email'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        amount_paid: {
            type: 'number',
            title: 'Amount Paid',
            default: 0
        }
    },
    type: 'object',
    required: [
        'link_id',
        'short_url',
        'amount',
        'status'
    ],
    title: 'PaymentLinkResponse',
    description: 'Response after creating or fetching a payment link.'
} as const;

export const PaymentLinkSyncResponseSchema = {
    properties: {
        link_id: {
            type: 'string',
            title: 'Link Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        amount_paid: {
            type: 'number',
            title: 'Amount Paid'
        },
        sheet_updated: {
            type: 'boolean',
            title: 'Sheet Updated',
            default: false
        }
    },
    type: 'object',
    required: [
        'link_id',
        'status',
        'amount',
        'amount_paid'
    ],
    title: 'PaymentLinkSyncResponse',
    description: 'Response after syncing a payment link status.'
} as const;

export const PaymentUpdateSchema = {
    properties: {
        razorpay_link_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Razorpay Link Id'
        },
        razorpay_link_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Razorpay Link Url'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: [
                        'pending',
                        'partial',
                        'paid',
                        'failed'
                    ]
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        amount_paid: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount Paid'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        last_reminder_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Reminder At'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'PaymentUpdate',
    description: 'Request body for updating a payment record. All fields optional.'
} as const;

export const SendReminderRequestSchema = {
    properties: {
        customer_email: {
            type: 'string',
            format: 'email',
            title: 'Customer Email'
        },
        reminder_level: {
            type: 'integer',
            title: 'Reminder Level',
            default: 1
        }
    },
    type: 'object',
    required: [
        'customer_email'
    ],
    title: 'SendReminderRequest',
    description: 'Request to send a payment reminder.\nOnly email is required — name, amount, payment_url etc.\nare looked up from the Payments sheet automatically.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
