// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Message
     *
     * The user's natural language input.
     */
    message: string;
    /**
     * Thread Id
     *
     * The conversation thread ID for LangGraph memory persistence.
     */
    thread_id?: string;
};

/**
 * Contact
 *
 * A contact in the Contacts sheet.
 */
export type Contact = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ContactCreate
 *
 * Request body for creating a new contact.
 */
export type ContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ContactUpdate
 *
 * Request body for updating a contact. All fields optional.
 */
export type ContactUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * CreatePaymentLinkRequest
 *
 * Request body for creating a Razorpay payment link.
 */
export type CreatePaymentLinkRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Min Partial Amount
     */
    min_partial_amount?: number | null;
    /**
     * Description
     */
    description: string;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Payment
 *
 * A payment record from the Payments sheet.
 */
export type Payment = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Description
     */
    description: string;
    /**
     * Razorpay Link Id
     */
    razorpay_link_id?: string | null;
    /**
     * Razorpay Link Url
     */
    razorpay_link_url?: string | null;
    /**
     * Status
     */
    status?: 'pending' | 'partial' | 'paid' | 'failed';
    /**
     * Amount Paid
     */
    amount_paid?: number;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Last Reminder At
     */
    last_reminder_at?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * PaymentCreate
 *
 * Request body for creating a new payment record.
 */
export type PaymentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Min Partial Amount
     */
    min_partial_amount?: number | null;
    /**
     * Description
     */
    description: string;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * PaymentLinkResponse
 *
 * Response after creating or fetching a payment link.
 */
export type PaymentLinkResponse = {
    /**
     * Link Id
     */
    link_id: string;
    /**
     * Short Url
     */
    short_url: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Customer Name
     */
    customer_name?: string | null;
    /**
     * Customer Email
     */
    customer_email?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Amount Paid
     */
    amount_paid?: number;
};

/**
 * PaymentLinkSyncResponse
 *
 * Response after syncing a payment link status.
 */
export type PaymentLinkSyncResponse = {
    /**
     * Link Id
     */
    link_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Amount Paid
     */
    amount_paid: number;
    /**
     * Sheet Updated
     */
    sheet_updated?: boolean;
};

/**
 * PaymentUpdate
 *
 * Request body for updating a payment record. All fields optional.
 */
export type PaymentUpdate = {
    /**
     * Razorpay Link Id
     */
    razorpay_link_id?: string | null;
    /**
     * Razorpay Link Url
     */
    razorpay_link_url?: string | null;
    /**
     * Status
     */
    status?: 'pending' | 'partial' | 'paid' | 'failed' | null;
    /**
     * Amount Paid
     */
    amount_paid?: number | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Last Reminder At
     */
    last_reminder_at?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * SendReminderRequest
 *
 * Request to send a payment reminder.
 * Only email is required — name, amount, payment_url etc.
 * are looked up from the Payments sheet automatically.
 */
export type SendReminderRequest = {
    /**
     * Customer Email
     */
    customer_email: string;
    /**
     * Reminder Level
     */
    reminder_level?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListContactsContactsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contacts';
};

export type ListContactsContactsGetResponses = {
    /**
     * Response List Contacts Contacts Get
     *
     * Successful Response
     */
    200: Array<Contact>;
};

export type ListContactsContactsGetResponse = ListContactsContactsGetResponses[keyof ListContactsContactsGetResponses];

export type CreateContactContactsPostData = {
    body: ContactCreate;
    path?: never;
    query?: never;
    url: '/contacts';
};

export type CreateContactContactsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContactContactsPostError = CreateContactContactsPostErrors[keyof CreateContactContactsPostErrors];

export type CreateContactContactsPostResponses = {
    /**
     * Successful Response
     */
    201: Contact;
};

export type CreateContactContactsPostResponse = CreateContactContactsPostResponses[keyof CreateContactContactsPostResponses];

export type SearchContactContactsSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         *
         * Contact name to search
         */
        name: string;
    };
    url: '/contacts/search';
};

export type SearchContactContactsSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchContactContactsSearchGetError = SearchContactContactsSearchGetErrors[keyof SearchContactContactsSearchGetErrors];

export type SearchContactContactsSearchGetResponses = {
    /**
     * Response Search Contact Contacts Search Get
     *
     * Successful Response
     */
    200: Contact | null;
};

export type SearchContactContactsSearchGetResponse = SearchContactContactsSearchGetResponses[keyof SearchContactContactsSearchGetResponses];

export type UpdateContactContactsEmailPutData = {
    body: ContactUpdate;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/contacts/{email}';
};

export type UpdateContactContactsEmailPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateContactContactsEmailPutError = UpdateContactContactsEmailPutErrors[keyof UpdateContactContactsEmailPutErrors];

export type UpdateContactContactsEmailPutResponses = {
    /**
     * Successful Response
     */
    200: Contact;
};

export type UpdateContactContactsEmailPutResponse = UpdateContactContactsEmailPutResponses[keyof UpdateContactContactsEmailPutResponses];

export type UpdateContactByNameContactsByNameNamePutData = {
    body: ContactUpdate;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/contacts/by-name/{name}';
};

export type UpdateContactByNameContactsByNameNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateContactByNameContactsByNameNamePutError = UpdateContactByNameContactsByNameNamePutErrors[keyof UpdateContactByNameContactsByNameNamePutErrors];

export type UpdateContactByNameContactsByNameNamePutResponses = {
    /**
     * Successful Response
     */
    200: Contact;
};

export type UpdateContactByNameContactsByNameNamePutResponse = UpdateContactByNameContactsByNameNamePutResponses[keyof UpdateContactByNameContactsByNameNamePutResponses];

export type ListPaymentsPaymentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payments';
};

export type ListPaymentsPaymentsGetResponses = {
    /**
     * Response List Payments Payments Get
     *
     * Successful Response
     */
    200: Array<Payment>;
};

export type ListPaymentsPaymentsGetResponse = ListPaymentsPaymentsGetResponses[keyof ListPaymentsPaymentsGetResponses];

export type CreatePaymentPaymentsPostData = {
    body: PaymentCreate;
    path?: never;
    query?: never;
    url: '/payments';
};

export type CreatePaymentPaymentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentPaymentsPostError = CreatePaymentPaymentsPostErrors[keyof CreatePaymentPaymentsPostErrors];

export type CreatePaymentPaymentsPostResponses = {
    /**
     * Successful Response
     */
    201: Payment;
};

export type CreatePaymentPaymentsPostResponse = CreatePaymentPaymentsPostResponses[keyof CreatePaymentPaymentsPostResponses];

export type SearchPaymentsPaymentsSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         *
         * Client email to search payments for
         */
        email: string;
    };
    url: '/payments/search';
};

export type SearchPaymentsPaymentsSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchPaymentsPaymentsSearchGetError = SearchPaymentsPaymentsSearchGetErrors[keyof SearchPaymentsPaymentsSearchGetErrors];

export type SearchPaymentsPaymentsSearchGetResponses = {
    /**
     * Response Search Payments Payments Search Get
     *
     * Successful Response
     */
    200: Array<Payment>;
};

export type SearchPaymentsPaymentsSearchGetResponse = SearchPaymentsPaymentsSearchGetResponses[keyof SearchPaymentsPaymentsSearchGetResponses];

export type UpdatePaymentPaymentsRowIndexPutData = {
    body: PaymentUpdate;
    path: {
        /**
         * Row Index
         */
        row_index: number;
    };
    query?: never;
    url: '/payments/{row_index}';
};

export type UpdatePaymentPaymentsRowIndexPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePaymentPaymentsRowIndexPutError = UpdatePaymentPaymentsRowIndexPutErrors[keyof UpdatePaymentPaymentsRowIndexPutErrors];

export type UpdatePaymentPaymentsRowIndexPutResponses = {
    /**
     * Successful Response
     */
    200: Payment;
};

export type UpdatePaymentPaymentsRowIndexPutResponse = UpdatePaymentPaymentsRowIndexPutResponses[keyof UpdatePaymentPaymentsRowIndexPutResponses];

export type CreatePaymentLinkRazorpayPaymentLinksPostData = {
    body: CreatePaymentLinkRequest;
    path?: never;
    query?: never;
    url: '/razorpay/payment-links';
};

export type CreatePaymentLinkRazorpayPaymentLinksPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaymentLinkRazorpayPaymentLinksPostError = CreatePaymentLinkRazorpayPaymentLinksPostErrors[keyof CreatePaymentLinkRazorpayPaymentLinksPostErrors];

export type CreatePaymentLinkRazorpayPaymentLinksPostResponses = {
    /**
     * Successful Response
     */
    201: PaymentLinkResponse;
};

export type CreatePaymentLinkRazorpayPaymentLinksPostResponse = CreatePaymentLinkRazorpayPaymentLinksPostResponses[keyof CreatePaymentLinkRazorpayPaymentLinksPostResponses];

export type GetPaymentLinkRazorpayPaymentLinksLinkIdGetData = {
    body?: never;
    path: {
        /**
         * Link Id
         */
        link_id: string;
    };
    query?: never;
    url: '/razorpay/payment-links/{link_id}';
};

export type GetPaymentLinkRazorpayPaymentLinksLinkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaymentLinkRazorpayPaymentLinksLinkIdGetError = GetPaymentLinkRazorpayPaymentLinksLinkIdGetErrors[keyof GetPaymentLinkRazorpayPaymentLinksLinkIdGetErrors];

export type GetPaymentLinkRazorpayPaymentLinksLinkIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaymentLinkResponse;
};

export type GetPaymentLinkRazorpayPaymentLinksLinkIdGetResponse = GetPaymentLinkRazorpayPaymentLinksLinkIdGetResponses[keyof GetPaymentLinkRazorpayPaymentLinksLinkIdGetResponses];

export type CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Link Id
         */
        link_id: string;
    };
    query?: never;
    url: '/razorpay/payment-links/{link_id}/cancel';
};

export type CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostError = CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostErrors[keyof CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostErrors];

export type CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: PaymentLinkResponse;
};

export type CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostResponse = CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostResponses[keyof CancelPaymentLinkRazorpayPaymentLinksLinkIdCancelPostResponses];

export type SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostData = {
    body?: never;
    path: {
        /**
         * Link Id
         */
        link_id: string;
    };
    query?: never;
    url: '/razorpay/payment-links/{link_id}/sync';
};

export type SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostError = SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostErrors[keyof SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostErrors];

export type SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostResponses = {
    /**
     * Successful Response
     */
    200: PaymentLinkSyncResponse;
};

export type SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostResponse = SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostResponses[keyof SyncPaymentLinkRazorpayPaymentLinksLinkIdSyncPostResponses];

export type RazorpayWebhookRazorpayWebhooksPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/razorpay/webhooks';
};

export type RazorpayWebhookRazorpayWebhooksPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendReminderEmailReminderPostData = {
    body: SendReminderRequest;
    path?: never;
    query?: never;
    url: '/email/reminder';
};

export type SendReminderEmailReminderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendReminderEmailReminderPostError = SendReminderEmailReminderPostErrors[keyof SendReminderEmailReminderPostErrors];

export type SendReminderEmailReminderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatEndpointChatPostData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat';
};

export type ChatEndpointChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatEndpointChatPostError = ChatEndpointChatPostErrors[keyof ChatEndpointChatPostErrors];

export type ChatEndpointChatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerRemindersRemindersTriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reminders/trigger';
};

export type TriggerRemindersRemindersTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetSystemResetPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/reset';
};

export type ResetSystemResetPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
